import type { Metadata } from 'next';
export const metadata: Metadata = {
  title: 'Hello World',
  description: 'Generated by create next app',
};
export default function Home() {
  return <div className="">home</div>;
}
