import { memo } from 'react';
import type { Metadata } from 'next';

const getUserData = (userid: string): Promise<string> => {
  return new Promise(resolve => {
    setTimeout(() => {
      resolve('获取用户信息' + userid);
    }, 10000);
  });
};

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};
const UserDetail = memo(({ params }: { params: { userid: string } }) => {
  const { userid } = params;
  const data = getUserData(userid);
  console.log('data...', data);
  metadata.title = 'hello world' + userid;
  return (
    <div>
      user detail：{userid}，{data}
    </div>
  );
});

UserDetail.displayName = 'UserDetail';

export default UserDetail;
